# Site settings
title: Andrés Pérez López
email: andres.perez@voicemod.net
description: "Andrés Pérez López personal website"
# baseurl: "/jekyll-example"
url: "http://andresperezlopez.github.io"
twitter_username: _aperezlopez
github_username:  andresperezlopez

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - "bower_components"
  - "node_modules"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "package.json"
  - "Rakefile"
  - "README.md"

include:
  - .nojekyll
