title: Andres Perez Lopez personal website
name: Andres Perez Lopez
email: andres.perez@upf.edu

description: >
  Personal website
url: "http://andresperezlopez.github.io"
twitter_username: _aperezlopez
github_username: andresperezlopez

markdown: kramdown
